name: Automate Docker Image Build and Push

on:
  push:
    branches: container-testing # TODO change to master
  pull_request:
    branches:
      - master
      - dev

env:
  IMAGE_NAME: autofocus-serve
  DOCKERFILE_DIR: autofocus/predict
  DOCKERHUB_USER: davidwilby # TODO change

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: AWS CLI install action
        uses: chrislennon/action-aws-cli@1.1
      -
        name: Load model file from AWS
        run: |
          aws s3 cp s3://autofocus/models/multilabel_model_20190407.pkl ${{ env.DOCKERFILE_DIR }}/models/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
            context: ${{ env.DOCKERFILE_DIR }}
            file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
            push: false
            tags: ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
      -
        name: Run docker container
        shell: bash
        run: |
            docker run -p 8000:8000 ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
      - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      -
        name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
            pip install requests
      -
        name: Test with pytest
        run: |
            pip install pytest
            pytest